---

# Run this playbook to see what hosts on your netork have ssh open on port 22
#
# Require variables:
#   subnet


- name: Provision alpine server from root account with login
  gather_facts: False
  hosts: localhost
  vars_files:
      - vars.yml
  become: yes

  tasks:

  - name: Run nmap on subnet to get devices running SSH
    shell: nmap -sS -O -p22 {{ subnet }} | grep "tcp open" -B 4
    register: nmap_output
    changed_when: False

  - name: Output of nmap
    debug: msg="{{ nmap_output.stdout_lines }}"
